# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the kernel character device drivers.
#

obj-$(CONFIG_RADIO_SI473X) += radio-si473x.o
obj-$(CONFIG_RADIO_SI476X) += radio-si476x.o

ccflags-y += -Isound
