# SPDX-License-Identifier: GPL-2.0
snd-soc-si473x-objs := si473x.o
snd-soc-si476x-objs := si476x.o
snd-soc-ssm2518-objs := ssm2518.o

obj-$(CONFIG_SND_SOC_SI473X)	+= snd-soc-si473x.o
obj-$(CONFIG_SND_SOC_SI476X)	+= snd-soc-si476x.o
obj-$(CONFIG_SND_SOC_SSM2518)	+= snd-soc-ssm2518.o
