#
# Makefile for radios with Silicon Labs Si473x FM Radio Receivers
#

si473x-core-objs	:= si473x-cmd.o si473x-prop.o si473x-i2c.o
snd-soc-si473x-objs	:= si473x.o

obj-m += radio-si473x.o
obj-m += si473x-core.o
obj-m += snd-soc-si473x.o
