# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices
#

si473x-core-y := si473x-cmd.o si473x-prop.o si473x-i2c.o
si476x-core-y := si476x-cmd.o si476x-prop.o si476x-i2c.o

obj-$(CONFIG_MFD_SI473X_CORE)	+= si473x-core.o
obj-$(CONFIG_MFD_SI476X_CORE)	+= si476x-core.o
